name: amd
channels:
  - conda-forge
  - pytorch
  - rdkit
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - ld_impl_linux-64=2.39
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libnsl=2.0.0
  - libsqlite=3.39.4
  - libuuid=2.32.1
  - libzlib=1.2.13
  - ncurses=6.3
  - openssl=3.0.5
  - pip=22.3
  - python=3.9.13
  - readline=8.2
  - setuptools=65.5.0
  - sqlite=3.39.4
  - tk=8.6.12
  - tzdata=2022e
  - wheel=0.37.1
  - xz=5.2.6
  - pip:
    - black==22.10.0
    - certifi==2022.9.24
    - charset-normalizer==2.1.1
    - click==8.1.3
    - idna==3.4
    - mypy-extensions==0.4.3
    - numpy==1.23.4
    - pandas==1.5.1
    - pathspec==0.10.1
    - platformdirs==2.5.2
    - python-dateutil==2.8.2
    - pytz==2022.5
    - requests==2.28.1
    - six==1.16.0
    - tomli==2.0.1
    - typing-extensions==4.4.0
    - urllib3==1.26.12
